/**
 * Freeze the token contract into `src/lib/theme/contractData.ts`.
 *
 *   node scripts/gen-theme-contract.ts
 *
 * Run it after editing `src/styles/tokens.css`; `themeContract.test.ts` fails
 * until the constant and the file agree again. The runtime cannot read the
 * stylesheet itself: vitest stubs every `.css` import (`?raw` included), and
 * the modules that need the contract — theme validation, the export palette —
 * sit under `appStore`, which half the suite imports.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseTokenContract } from "../src/lib/theme/contract.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(root, "src/styles/tokens.css"), "utf8");
const contract = parseTokenContract(css);

const out = `/* GENERATED by scripts/gen-theme-contract.ts from src/styles/tokens.css — do not edit by hand.
   themeContract.test.ts fails when this drifts from the stylesheet; re-run the script. */
import type { TokenContract } from "./contract";

export const TOKEN_CONTRACT: TokenContract = ${JSON.stringify(contract, null, 2)};
`;
writeFileSync(join(root, "src/lib/theme/contractData.ts"), out);
console.log(
  `contractData.ts: ${contract.scale.length} scale · ${contract.core.length} core · ${contract.derived.length} derived · hand-tuned ${Object.keys(contract.handTuned).join(", ")}`,
);
